openapi: '3.0.0'
info:
  title: MileApp API Documentation
  version: '3.0.0'
  termsOfService: 'https://mile.app/terms-conditions/'
  contact:
    email: support@mile.app
    url: 'https://apidoc.mile.app/'
  x-logo:
    url: 'https://apidoc.mile.app/themes/assets/img/mileapp.png'
  description: |
    MileApp API Documentation - RESTful API for field operations management.

servers:
  - url: https://apiweb.mile.app/api/v3
    description: Production

security:
  - bearerAuth: []

tags:
  - name: Task
    description: Task management endpoints
  - name: Bulk Operations
    description: Bulk task operations
  - name: Vehicle
    description: Vehicle management for route optimization
  - name: Routing
    description: Route optimization endpoints
  - name: Flow
    description: Mobile workflow management
  - name: Automation
    description: Event-driven automation
  - name: Data Source
    description: Data source management
  - name: User
    description: User management
  - name: Hub
    description: Hub management

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Use a valid Bearer token to authenticate. Include in Authorization header using Bearer <token> format.

paths:
